apostolic_passwd: ENC[AES256_GCM,data:EfYau8loSV8WaIFzXhNm73+g2wUYeOjxkP3Qaq/93VWV1ILhc2b1+SgAfFnuB43KNoJcgvO7tNA8d45rTQLg2VMC+g6TjiqC3w==,iv:XnI3dGMi2D3LFLF20GsnO+4lS1D7HaODT9v2Q+IGsAQ=,tag:T9xHNzJpXLZpqT5FeLCN9A==,type:str]
sops:
    age:
        - recipient: age1qy2xnw79k2xuld9vdzffef05pa9u7uuvn9awlepp03pfvvwksd3ss6e372
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K1Q1bEVBNmU4bEZDUy9E
            STNFb3NIWDJEb3JmelErMGxmZ2paMFY3NVY4CnNVazBHYmx2V2pIaWVxWVlYaTda
            a0VSSytFcUJXQmNKS2crR2NhWFAyMk0KLS0tIDJBbGFOcTRaZlBQYUtqTG9MUDIz
            UFdRSDVONmx2T0QyaENLakVhZFlDQUkKLmhTqbF5Y8HbMPkwMraEhXOhhvIYQGYs
            2CN3cfdFcWFGoOhTkAZHhynKw3GvbIXcO5GV47JlaMah6xBCUxeSVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T14:27:23Z"
    mac: ENC[AES256_GCM,data:GehaSEDnOAl4bviXkk9+I0OKYAY2Wte3spSAljeuUI5MeVvNq/Y3KMG3mFPtAx6IJmrUfugr6Rm5hD4X4qtSozrgUfKjzuCN4xqmUo7glU94d2IPZ2fl/KOOAZog2FquA4tgO3ewL/F7IByyVjCRFXhpirxT6nidHyngby/n3eQ=,iv:O8QBgqit02gLcrYCqP5aE9j5geyvBeIERP7jke/7XZg=,tag:9Y2k4AbREdvSOcNmha2paA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
