{
  services.zapret = {
    enable = true;
    httpSupport = false;
    udpSupport = true;
    udpPorts = [ "443" ];
    configureFirewall = true;
    whitelist = [
      "medium.com"
      "myanimelist.net"
      "soundcloud.com"
      "musicbrainz.org"
      "picard.musicbrainz.org"
      "flibusta.is"
      "audiobookbay.lu"
      "goodreads.com"
      "cloudflare-ech.com"
      "news.google.com"
      "zona.media"
      "svtv.org"
      "catbox.moe"
      "dis.gd"
      "discord-attachments-uploads-prd.storage.googleapis.com"
      "discord.app"
      "discord.co"
      "discord.com"
      "discord.design"
      "discord.dev"
      "discord.gift"
      "discord.gifts"
      "discord.gg"
      "discord.media"
      "discord.new"
      "discord.store"
      "discord.status"
      "discord-activities.com"
      "discordactivities.com"
      "discordapp.com"
      "discordapp.net"
      "discordcdn.com"
      "discordmerch.com"
      "discordpartygames.com"
      "discordsays.com"
      "discordsez.com"
      "yt3.ggpht.com"
      "yt4.ggpht.com"
      "yt3.googleusercontent.com"
      "googlevideo.com"
      "jnn-pa.googleapis.com"
      "stable.dl2.discordapp.net"
      "wide-youtube.l.google.com"
      "youtube-nocookie.com"
      "youtube-ui.l.google.com"
      "youtube.com"
      "youtubeembeddedplayer.googleapis.com"
      "youtubekids.com"
      "youtubei.googleapis.com"
      "youtu.be"
      "yt-video-upload.l.google.com"
      "ytimg.com"
      "ytimg.l.google.com"
      "frankerfacez.com"
      "ffzap.com"
      "betterttv.net"
      "7tv.app"
      "7tv.io"
      "manifest.googlevideo.com"
      "googlevideo.com"
    ];
    params = [
      "--dpi-desync=fake,disorder2"
      "--dpi-desync-ttl=1"
      "--dpi-desync-autottl=-1"
      "--dpi-desync-fooling=badsum,badseq,md5sig,ts"
      "--dpi-desync-fake-tls=0x00000000"
      "--dpi-desync-repeats=6"
    ];
  };
}
